
CREATE TABLE ENDERECO_EMPRESA
(
  COD_EMPRESA                           int      NOT NULL,
  DATA_VIGENCIA                         datetime NOT NULL,
  DATA_INICIO_VIGENCIA_ENDERECO_EMPRESA datetime NOT NULL,
  DATA_FIM_VIGENCIA_ENDERECO_EMPRESA    datetime,
  CONSTRAINT PK_ENDERECO_EMPRESA PRIMARY KEY (COD_EMPRESA, DATA_VIGENCIA, DATA_INICIO_VIGENCIA_ENDERECO_EMPRESA)
)
GO

CREATE TABLE RESPONSAVEL_EMPRESA
(
  COD_EMPRESA                              int      NOT NULL,
  DATA_VIGENCIA                            datetime NOT NULL,
  DATA_INICIO_VIGENCIA_RESPONSAVEL_EMPRESA datetime NOT NULL,
  DATA_FIM_VIGENCIA_RESPONSAVEL_EMPRESA    datetime,
  CONSTRAINT PK_RESPONSAVEL_EMPRESA PRIMARY KEY (COD_EMPRESA, DATA_VIGENCIA, DATA_INICIO_VIGENCIA_RESPONSAVEL_EMPRESA)
)
GO

CREATE TABLE TAB32_EMPRESA
(
  COD_EMPRESA      int      NOT NULL,
  DATA_VIGENCIA    datetime NOT NULL,
  CNPJ             text    ,
  SITUACAO_EMPRESA int      NOT NULL,
  CONSTRAINT PK_TAB32_EMPRESA PRIMARY KEY (COD_EMPRESA, DATA_VIGENCIA)
)
GO

ALTER TABLE RESPONSAVEL_EMPRESA
  ADD CONSTRAINT FK_TAB32_EMPRESA_TO_RESPONSAVEL_EMPRESA
    FOREIGN KEY (COD_EMPRESA, DATA_VIGENCIA)
    REFERENCES TAB32_EMPRESA (COD_EMPRESA, DATA_VIGENCIA)
GO

ALTER TABLE ENDERECO_EMPRESA
  ADD CONSTRAINT FK_TAB32_EMPRESA_TO_ENDERECO_EMPRESA
    FOREIGN KEY (COD_EMPRESA, DATA_VIGENCIA)
    REFERENCES TAB32_EMPRESA (COD_EMPRESA, DATA_VIGENCIA)
GO
